version: "3"

services:
  server:
    container_name: squareboat_backend
    build:
      context: ./squareboat_backend
      dockerfile: dockerfile
    environment:
      HOST: 0.0.0.0  
      REDIS_URL: redis://cache
    ports:
      - 3001:3001
    volumes:
      - ./squareboat_backend:/src/server/app/squareboat_backend
    working_dir: /src/server/app
    env_file:
      - ./squareboat_backend/.env

  client:
    container_name: squareboat-frontend
    build:
      context: ./squareboat-frontend
      dockerfile: dockerfile
    environment:
      HOST: 0.0.0.0
    ports:
      - 3002:3002
    volumes:
      - ./squareboat-frontend:/src/client/app/squareboat-frontend
    working_dir: /src/client/app
    env_file:
      - ./squareboat-frontend/.env

#   cache:
#     image: redis:6.2-alpine
#     restart: on-failure
#     ports:
#       - '6379:6379'
#     environment:
#       REDIS_HOST: cache
#       REDIS_PORT: 6379
#       REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     volumes: 
#       - cache:/data
# volumes:
#   cache:
#     driver: local

  
  # redis:
  #   image: redis
  #   container_name: redis-server
  #   expose:
  #     - 6379
